### ISSUE TITLE
Modify citation format to be compatible with DataCite

### ISSUE THREAD

**Issue by charuleka** [NGEET/ngt-archive#318]
This is the suggested citation format in DataCite 4.1. We should adopt this for our citation format. Pasting recommendations from DataCite

The following is the preferred format for rendering a DataCite citation for human readers using the
mandatory properties of the schema:
Creator (PublicationYear): Title. Publisher. (resourceTypeGeneral). Identifier

It may also be desirable to include information from optional properties, such as Version. This is
particularly important to include when citing software. For example:

Creator (PublicationYear): Title. Version. Publisher. (resourceTypeGeneral). Identifier

For citation purposes, DataCite prefers that DOI names are displayed as linkable, permanent URLs. 

The Identifier may appear in its original format. If the original format is chosen, be sure to include the characters “doi:" pre-pended to the Identifier as in “doi:10.1234/abc.”
For resources that do not have a standard publication year value, DataCite suggests that PublicationYear should include the date that is preferred for use in a citation.

Here are several examples:
● Irino, T; Tada, R (2009): Chemical and mineral compositions of sediments from ODP Site 127-797.
V. 2.1. Geological Institute, University of Tokyo. (dataset).
https://doi.org/10.1594/PANGAEA.726855
● Geofon operator (2009): GEFON event gfz2009kciu (NW Balkan Region). GeoForschungsZentrum
Potsdam (GFZ). (dataset). https://doi.org/10.1594/GFZ.GEOFON.gfz2009kciu
● Denhard, Michael (2009): dphase_mpeps: MicroPEPS LAF-Ensemble run by DWD for the MAP DPHASE project. World Data Center for Climate. (dataset.) https://doi.org/10.1594/WDCC/dphase_mpeps

**Comment by vchendrix** [comment]
What about multiple authors?

**Comment by charuleka** [comment]
Follow example 1.

**Comment by vchendrix** [comment]
Doh.  I see now.
