### ISSUE TITLE
Methods Field Change

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#332]
Change "QA/QC Method" field to just "Methods"

**Comment by vchendrix** [comment]
@emilyarobles @charuleka I would love to get to these issues as a part of the work I am doing now on the spin transition.  Would it be possible for us to get a team together to come up with a testing plan?

**Comment by emilyarobles** [comment]
"Methods Description" is not showing on the landing page, only a colon.
![image](https://user-images.githubusercontent.com/46009925/98411095-4bf51400-202a-11eb-979f-770b8b0ea765.png)

**Comment by vchendrix** [comment]
@emilyarobles I made the fix you suggested.  Have a look https://ngt-dev.lbl.gov/dois/NGT0052/

**Comment by emilyarobles** [comment]
The change is showing correctly now.
