### ISSUE TITLE
References on landing page

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#333]
The data package landing pages are not showing related references. Instead, it's displaying the dataset citation under both  "Reference" and "Dataset Citation." We need the "Dataset Reference(s)" field from the data package submission page to show on the DOI landing page. 
![image](https://user-images.githubusercontent.com/46009925/78409072-a3776100-75bd-11ea-8ea4-dc154bf67e18.png)

**Comment by emilyarobles** [comment]
Test was successful.

**Comment by vchendrix** [comment]
not merged to master yet. repoening
