### ISSUE TITLE
Adding metadata template documentation and adding PDFs instead of GDocs

### ISSUE THREAD

**Issue by gilbertozp** [NGEET/ngt-archive#356]
The [Metadata Template](https://docs.google.com/document/d/1WwYEb9QvzLvVLE4mM2fX07NO2urERv2YNGGghd-lqoM/) is a helpful quick reference document for someone creating a dataset. Adding a link to it in the Archive menus will help make it accessible.

We also elected to change the format for both the currently linked [Help Documentation](https://docs.google.com/document/d/14idE53T_HyE5a9jaIGcdnW1zvg6WwT9bBY9aF7BfE3c/edit) and the [Metadata Template](https://docs.google.com/document/d/1WwYEb9QvzLvVLE4mM2fX07NO2urERv2YNGGghd-lqoM/) from GDocs to PDFs. Emily will add the PDFs to be linked to this issue.

The two options discussed for the menu structure are:
- Keeping single level and just adding new template to menu: `[Help Documentation | Metadata Guidelines | Contact]`
- Adding sub-menus, with two levels: `Help -> [Documentation | Metadata Guidelines]`

**Comment by emilyarobles** [comment]
PDFs:
[NGEE-Tropics Metadata Guidelines.pdf](https://github.com/NGEET/ngt-archive/files/8336775/NGEE-Tropics.Metadata.Guidelines.pdf)
[NGEE Tropics Help Documentation.pdf](https://github.com/NGEET/ngt-archive/files/8336776/NGEE.Tropics.Help.Documentation.pdf)

**Comment by vchendrix** [comment]
> PDFs: [NGEE-Tropics Metadata Guidelines.pdf](https://github.com/NGEET/ngt-archive/files/8336775/NGEE-Tropics.Metadata.Guidelines.pdf) [NGEE Tropics Help Documentation.pdf](https://github.com/NGEET/ngt-archive/files/8336776/NGEE.Tropics.Help.Documentation.pdf)

@emilyarobles @gilbertozp I just noticed that this issue has not been handled.   Do you want me to link to the PDFs in GDocs or have a static copy of the PDFs checked in with the code?  I am inclined towards the latter.

**Comment by gilbertozp** [comment]
@vchendrix I also like adding the PDFs with the code. Thanks for catching this one.
