### ISSUE TITLE
Automatic Upload of Locations Reporting Format with NGT to ESS-DIVE Transfer

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#372]
The NGEE-Tropics archive has additional site information that isn't captured by the package level metadata on ESS-DIVE. The [reporting format for location metadata](https://github.com/ess-dive-community/essdive-location-metadata) can be used to preserve this information. 

Proposed flow:
1. Dataset is approved and published on NGEE-Tropics
2. Dataset is transferred to ESS-DIVE 
3. During transfer, an additional CSV file with location metadata is uploaded along with the original 
4. If a dataset has multiple sites listed, a CSV file for each site will be uploaded
5. Final dataset on ESS-DIVE will have a locations CSV and the original zip file of NGEE-Tropics data 

[Location Reporting Format Template](https://github.com/ess-dive-community/essdive-location-metadata/blob/main/templates/Location_metadata_template.csv)
[NGEE-Tropics Site/Plot Information](https://ngt-data.lbl.gov/?view=view-sites)
[NGEE-Tropics Site to Location Reporting Format Crosswalk](https://docs.google.com/spreadsheets/d/1SSA2uf0fnqk9coGk4jPHtaydyDvkFEg1Bszbn6ExF7E/edit#gid=0)

**Comment by vchendrix** [comment]
@emilyarobles I think I need a crosswalk of how you would like the NGEE Tropics sites to be mapped onto the locations reporting format?  

Some questions that need to be answered:

- Are there any fields we can ignore? Should I stick to the required fields for now?
- How do we hancle multiple contacts?  Why is is called Submission_Contact? is that the same thing as the the site contact or is it something else?

**Comment by vchendrix** [comment]
Change transfer of locations to happen during the metadata transfer.

**Comment by vchendrix** [comment]
@emilyarobles reminder to update note field format for locations.csv

**Comment by emilyarobles** [comment]
The notes section should have the following text, if the information is available for the site:
"Site URL(s): [**site_urls**]; Location Map URL: [**location_map_urls**]; State Province: [**state_province**]"

**Comment by vchendrix** [comment]
> @vchendrix The notes section should have the following text, if the information is available for the site: "Site URL(s): [**site_urls**]; Location Map URL: [**location_map_urls**]; State Province: [**state_province**]"

How do you want the size information for plots formatted?

**Comment by vchendrix** [comment]
@emilyarobles for plot size how about

"Site URL(s): [site_urls]; Location Map URL: [location_map_urls]; State Province: [state_province]; Plot Size: [size]"

**Comment by vchendrix** [comment]
@emilyarobles on second though.  I think the plot format for notes should be. There should be no need to repeat the site information since it will also be in the csv

"Plot Location KMZ URL: [location_kmz_urls]; Plot Country: [country]; Plot Size: [size]"

**Comment by emilyarobles** [comment]
@vchendrix Ah that's right - forgot about plots. The second option looks good, I agree that site info would be unnecessary
