### ISSUE TITLE
Location Reporting Format File Name

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#381]
Consider adding NGEE-Tropics identifier to the locations csv file name (currently locations.csv for each dataset).

Eg. NGT0149_locations.csv 

This is related to #372

**Comment by gilbertozp** [comment]
Consider same convention for other automatically generated files as well (e.g., long acknowledgements)

**Comment by gilbertozp** [comment]
N.B.: with this change, previously generated files in ESS-DIVE will need to be removed manually
