### ISSUE TITLE
Generate acknowledgements text file when ESS-DIVE abstract limit reached

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#387]
The NGEE-Tropics Acknowledgements field is combined with the Dataset Description when transferred to the ESS-DIVE Abstract field. The ESS-DIVE Abstract has a limit of 5,000 characters. Generating a text file for the content of the acknowledgements field will preserve the acknowledgements while avoiding failed transfers because of the character limit. The acknowledgements.txt file should include the exact text as entered in the NGEE-Tropics Acknowledgements field. 

**acknowledgements.txt should be generated when**
- Dataset description character count + Acknowledgements character count + **139** > 5,000 characters.
The additional 139 characters represents the automated sentence and "Acknowledgements: " added to the ESS-DIVE abstract field when an NGEE-Tropics dataset is transferred. 

**Proposed additional sentence**
When an acknowledgements.txt file is generated because the 5,000 character limit has been reached, a standard message should be added to the end of the ESS-DIVE abstract:

"Please see the acknowledgements.txt file for a full listing of dataset acknowledgements."

**Additional information**

The dataset that began this discussion was NGT0201, which included a very long acknowledgements field (6,706 characters). This pushed the ESS-DIVE abstract far passed the 5,000 character maximum, resulting in a failed transfer. The majority of NGEE-Tropics datasets have an ESS-DIVE abstract of less than 2,000 characters, with an average of 1,395.
<img width="487" alt="Screen Shot 2023-04-06 at 2 34 55 PM" src="https://user-images.githubusercontent.com/46009925/230498283-6ab0c595-81ab-4b6f-9dae-62e94444990c.png">

<img width="402" alt="Screen Shot 2023-04-06 at 2 37 34 PM" src="https://user-images.githubusercontent.com/46009925/230498666-6a1e7b8e-a850-47e7-969e-dad0986f0ff7.png">

**Comment by emilyarobles** [comment]
@vchendrix would it be possible to add the NGT ID to the text file name, similarly to the locations csv file? The name would also need to be reflected in the "Proposed additional sentence" in the abstract (eg. NGT0201_acknowledgements.txt).

**Comment by vchendrix** [comment]
> NGT0201_acknowledgements.txt

Yes!
