### ISSUE TITLE
Consider making Method Description a required field

### ISSUE THREAD

**Issue by gilbertozp** [NGEET/ngt-archive#397]
Methods is a required field for ESS-DIVE, so it might be useful to add our "Method Description" field to the list of required fields (instead of current optional status). This would avoid us having to request methods (or manually populate from description)  in review phase.

 @emilyarobles, how does this sound to you?

**Comment by gilbertozp** [comment]
For consistency with long-term preservation requirements, it would be good to add a check for the Description field so that it has at least 100 words.

**Comment by vchendrix** [comment]
@emilyarobles Do you agree with this requirement?

**Comment by emilyarobles** [comment]
Just to confirm, this is for the Method Description field right?

**Comment by vchendrix** [comment]
@emilyarobles Yes, this is for Method Description.  Do you mind if I just put a character minium?  Rather than count words?  What would you suggest it be in characters?

**Comment by vchendrix** [comment]
Actually, @gilbertozp and @emilyarobles. Since I can't actually change the database configuration on this field (there are 44 datasets with no method descriptions) I will have to just add the check in the Javascript.  This will only mark the field as required.  Will that suffice?

**Comment by vchendrix** [comment]
@emilyarobles I should be able to do the word count....

**Comment by vchendrix** [comment]
@emilyarobles @gilbertozp The following published datasets with access level that is either NGEE Tropics or public have no Method description

```
ngeet=# select ngt_id, status, access_level, name from archive_api_dataset where qaqc_method_description is null and status >0 and access_level >0 order by ngt_id;
 ngt_id | status | access_level |                                                          name                                                          
--------+--------+--------------+------------------------------------------------------------------------------------------------------------------------
     13 |      2 |            2 | Leaf surface temperature and sapflow raw data, 11 March 2016 - 13 June 2016, Santarem Brazil, Km67 tower
     17 |      2 |            2 | Sapflow, Soil Water Content, Leaf Surface Temperature, San Lorenzo, Panama (PA-SLZ), 2015 - 201606
     20 |      2 |            2 | Global 4 km resolution monthly gridded Gross Primary Productivity (GPP) data set dervied from FLUXNET2015
     22 |      2 |            2 | PNM sapflow, leaf surface temp, soil TDR 2016-09-21
     49 |      2 |            1 | FAST sensitivity analysis
    124 |      2 |            2 | Raw leaf gas exchange data in the Amazon basin, 2014-2016
    127 |      2 |            2 | Raw leaf isoprene and monoterpene emission GC-MS chromatograms/calibrations for MassHunter software, Brazil, 2014-2016
```
