### ISSUE TITLE
Error transferring dataset to ESS-DIVE at (or within) the limit of characters for at least three fields

### ISSUE THREAD

**Issue by gilbertozp** [NGEET/ngt-archive#398]
It seems there are small mismatches at the character limits for transfers of certain fields from the NGEE-Tropics Archive to ESS-DIVE in addition to Description.

The example below fails transfer, and the error message lists three fields with errors (ESS-DIVE label / NGEE-Tropics label):
- citation / DATASET REFERENCES
- Additional information about citations / ADDITIONAL INFORMATION ABOUT DATASET REFERENCES
- measurementTechnique / METHOD DESCRIPTION

For more detail, transfer failure log for dataset NGT0096 on Dev: /admin/archive_api/essdivetransfer/170/change/

**Comment by vchendrix** [comment]
> citation / DATASET REFERENCES
> Additional information about citations / ADDITIONAL INFORMATION ABOUT DATASET REFERENCES

Both of these go into the ESS-DIVE `Dataset.citation` field which accepts a string array with strings <= 1024 characters


anyOf -> | stringmaxLength: 1024minLength: 1[uniqueItems: truestringmaxLength: 1024minLength: 1]
-- | --



> measurementTechnique / METHOD DESCRIPTION

This goes into the ESS-DIVE `Dataset.measurementTechnique` field which accepts a string array with strings <= 5000 characters


anyOf -> | stringmaxLength: 5000minLength: 1[stringmaxLength: 5000minLength: 1]
-- | --


The dataset in error had

+  _`citation` with 11 strings and none of them had a length > 1024._ However, there are only 8 unique strings means that there are two sets of duplicates which would raise and exception
+ _`measurementTechnique` with 1 string > 5000 characters._  The latter is definitely in error but the former does not seem to be problemantic.  There are a bunch of `\\n\\n` characters found in the json string which is strange.

**Comment by vchendrix** [comment]
The citation error likely won't happen. However, a bug was found in transfering `measurementTechnique`.  It is not spliting the string on newlines.
