### ISSUE TITLE
Error accessing dataset download log

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#401]
### Issue
There is a Server Error (500) appearing when trying to access the dataset download log (https://ngt-data.lbl.gov/admin/archive_api/datasetdownloadlog/) from the NGT admin page (https://ngt-data.lbl.gov/admin/). No other pages are experiencing this issue.

**Comment by vchendrix** [comment]
The following error is thrown in the logs

```
NotImplementedError: subclasses of ListFilter must provide an expected_parameters() method
[pid: 1|app: 0|req: 9292/9972] 10.42.8.48 () {66 vars in 2587 bytes} [Mon May 15 15:22:32 2023] GET /admin/archive_api/datasetdownloadlog/ => generated 145 bytes in 12 msecs (HTTP/1.0 500) 7 headers in 255 bytes (1 switches on core 0)
```
