### ISSUE TITLE
ESS-DIVE Transfer Error - Identifier Not Matching

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#408]
When transferring datasets that were previously successfully transferred to ESS-DIVE, we are getting a failed status and the error message ([example dataset NGT0172](https://ngt-data.lbl.gov/admin/archive_api/essdivetransfer/257/change/)):

_{"detail": "DataPackage with id 'ess-dive-39cfdd1f074e5bc-20220608T192353847938' is an old version and cannot be updated. If the problem persists, contact ess-dive-support@lbl.gov if you need further assistance."}_

It is expected that the ESS-DIVE identifiers would be automatically updated. For the example dataset above, the new ESS identifier is[ ess-dive-9308cdaab8456e8-20230407T151919259803](https://data.ess-dive.lbl.gov/view/ess-dive-9308cdaab8456e8-20230407T151919259803).

**Comment by vchendrix** [comment]
Addressed in 667575692cc6502e232f2c5288ff471497e079fd.  Closing
