### ISSUE TITLE
Issue error message in admin UI when trying to sync datasets in non-approved state

### ISSUE THREAD

**Issue by gilbertozp** [NGEET/ngt-archive#409]
In the Admin UI, when trying to synchronize a dataset in a "submitted" state to ESS-DIVE ("Transfer dataset [metadata+]data to ESS-DIVE), the transfer will be attempted and fail (no publication date error from ESS-DIVE). This should probably not be attempted, issuing the error in the Admin UI like other error messages (e.g., trying to sync OSTI info without publication date).

**Comment by vchendrix** [comment]
Closed wrog issue
