### ISSUE TITLE
Change description word error to < 100 words (Release 3.2.0-rc3)

### ISSUE THREAD

**Issue by emilyarobles** [NGEET/ngt-archive#421]
Release 3.2.0-rc3 includes a minimum word count restriction for the Dataset Description field. It currently gives a warning when a description has less than or exactly 100 words. 

We would like to change this so that the restriction flags only descriptions with less than 100 words and accepts 100 words exactly (change from <= 100 to <100).

**Comment by vchendrix** [comment]
@emilyarobles I am using `< 100`

See https://github.com/NGEET/ngt-archive/blob/main/archive_api/serializers.py#L149-L151

```python
       # Make sure description has at least 100 words
        if 'description' in data.keys() and data['description'] and len(data['description'].split()) < 100:
            errors["description"] = "Description must be at least 100 words."
```

**Comment by vchendrix** [comment]
@emilyarobles can you give me some text that your entered which I can used to reproduce the issue you are seeing?

**Comment by emilyarobles** [comment]
@vchendrix This description is 100 words but the error is appearing:

> Revising to add text and meet 100 word limit, error message appeared as expected: This dataset contains raw output from the data logger connected to 9 sapflow and 5 soil moisture sensors are provided in the file xxx.dat. The metadata file (BR-Ma2 E-field log_20160501.xls) has additional information on locations where the sensors were installed, as well as other installation/maintenance details. No data processing or QA/QC was done on the raw datasets. Additional processed datasets will be uploaded separately and added to the Dataset References section. Please contact janedoe@lbl.gov if you need to use this dataset for additional information.

>

**Comment by vchendrix** [comment]
@emilyarobles I using a very simple way to count words with split().  Here is how that text appears

```python
>>> text = """Revising to add text and meet 100 word limit, error message appeared as expected: This dataset contains raw output from the data logger connected to 9 sapflow and 5 soil moisture sensors are provided in the file xxx.dat. The metadata file (BR-Ma2 E-field log_20160501.xls) has additional information on locations where the sensors were installed, as well as other installation/maintenance details. No data processing or QA/QC was done on the raw datasets. Additional processed datasets will be uploaded separately and added to the Dataset References section. Please contact janedoe@lbl.gov if you need to use this dataset for additional information."""
>>> len(text.split())
98
>>> text.split()
['Revising', 'to', 'add', 'text', 'and', 'meet', '100', 'word', 'limit,', 'error', 'message', 'appeared', 'as', 'expected:', 'This', 'dataset', 'contains', 'raw', 'output', 'from', 'the', 'data', 'logger', 'connected', 'to', '9', 'sapflow', 'and', '5', 'soil', 'moisture', 'sensors', 'are', 'provided', 'in', 'the', 'file', 'xxx.dat.', 'The', 'metadata', 'file', '(BR-Ma2', 'E-field', 'log_20160501.xls)', 'has', 'additional', 'information', 'on', 'locations', 'where', 'the', 'sensors', 'were', 'installed,', 'as', 'well', 'as', 'other', 'installation/maintenance', 'details.', 'No', 'data', 'processing', 'or', 'QA/QC', 'was', 'done', 'on', 'the', 'raw', 'datasets.', 'Additional', 'processed', 'datasets', 'will', 'be', 'uploaded', 'separately', 'and', 'added', 'to', 'the', 'Dataset', 'References', 'section.', 'Please', 'contact', 'janedoe@lbl.gov', 'if', 'you', 'need', 'to', 'use', 'this', 'dataset', 'for', 'additional', 'information.']
>>> 
```

**Comment by vchendrix** [comment]
Closing.
