### ISSUE TITLE
Add keyword  “ESS-DIVE Location Metadata Reporting Format” to datasets metadata

### ISSUE THREAD

**Issue by gilbertozp** [NGEET/ngt-archive#436]
ESS-DIVE uses a keyword  (“ESS-DIVE Location Metadata Reporting Format”) to sign that a dataset contains the location reporting format file within the dataset's data files. We need to update this metadata field for all NGEE-Tropics datasets in ESS-DIVE.

**Comment by vchendrix** [comment]
Close in 1dbd96b04e672ecc32ab18e4d23587c544e464d8
